name: Deploy to Cloud Foundry
on:
  push:
    branches:
    - main
jobs:
    Docker:
      runs-on: ubuntu-latest
      container: ppiper/cf-cli:latest
      steps:
      - name: Piper        
        run: |
          docker run ppiper/cf-cli cf --help
