name: Deploy to Cloud Foundry
on:
  push:
    branches:
    - main
jobs:
    Docker:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Use Node.js
          uses: actions/setup-node@v1
          with:
            node-version: 16      
        - name: Docker
          run: |
            docker pull ppiper/cf-cli:latest
            docker run --name ppiper -it -d ppiper/cf-cli
            docker exec -it ppiper bash
            cf login
  
