name: Deploy to Cloud Foundry
on:
  push:
    branches:
    - main
jobs:
    Docker:
      runs-on: ubuntu-latest
      container: ppiper/cf-cli:latest
      steps:
        - run: echo "Ppiper"

        - uses: actions/checkout@v3

        - uses: actions/setup-node@v3
          with:
            node-version: '16'
            cache: 'npm'        
  
