name: Deploy to Cloud Foundry
on:
  push:
    branches:
    - main
jobs:
    Docker:
      runs-on: ubuntu-latest
      container: ppiper/cf-cli:latest
      steps:
      - name: Piper
        shell: bash
        run: |
          cf login
